drop table if exists anime cascade ;
drop table if exists characters cascade ;
drop table if exists staff cascade ;
drop table if exists anime cascade ;
drop table if exists characters cascade ;
drop table if exists staff cascade ;
drop table if exists anime cascade ;
drop table if exists characters cascade ;
drop table if exists staff cascade ;
drop table if exists anime;
drop table if exists characters;
drop table if exists staff;
drop table if exists anime;
drop table if exists characters;
drop table if exists staff;
drop table if exists anime;
drop table if exists characters;
drop table if exists staff;
drop table if exists anime;
drop table if exists characters;
drop table if exists staff;
drop table if exists anime;
drop table if exists characters;
drop table if exists staff;
drop table if exists anime;
drop table if exists characters;
drop table if exists staff;
